USE `medic9ue_medi_data`;

-- Añadiendo campos de RRHH a las demás tablas de empleados
ALTER TABLE `nurse`
  ADD COLUMN `id_user` int(11) DEFAULT NULL,
  ADD COLUMN `num_empleado` varchar(50) DEFAULT NULL,
  ADD COLUMN `tipo_empleado` varchar(50) DEFAULT 'Permanente',
  ADD COLUMN `duracion_contrato` varchar(100) DEFAULT NULL,
  ADD COLUMN `fecha_ingreso` date DEFAULT NULL,
  ADD COLUMN `id_departamento` int(11) DEFAULT NULL,
  ADD COLUMN `id_cargo` int(11) DEFAULT NULL,
  ADD COLUMN `id_horario` int(11) DEFAULT NULL,
  ADD COLUMN `id_salary_level` int(11) DEFAULT NULL,
  ADD COLUMN `salario` decimal(10,2) DEFAULT NULL,
  ADD COLUMN `cuenta_bac` varchar(50) DEFAULT NULL,
  ADD COLUMN `telefono` varchar(20) DEFAULT NULL,
  ADD COLUMN `correo_personal` varchar(100) DEFAULT NULL,
  ADD COLUMN `correo_institucional` varchar(100) DEFAULT NULL,
  ADD COLUMN `num_locker` varchar(20) DEFAULT NULL,
  ADD COLUMN `id_biometrico` int(11) DEFAULT NULL,
  ADD COLUMN `url_contrato` longblob DEFAULT NULL,
  ADD COLUMN `url_solicitud` longblob DEFAULT NULL,
  ADD COLUMN `url_psicometricas` longblob DEFAULT NULL,
  ADD COLUMN `id_candidate_rrhh` int(11) DEFAULT NULL;

ALTER TABLE `staff_general_services`
  ADD COLUMN `id_user` int(11) DEFAULT NULL,
  ADD COLUMN `num_empleado` varchar(50) DEFAULT NULL,
  ADD COLUMN `tipo_empleado` varchar(50) DEFAULT 'Permanente',
  ADD COLUMN `duracion_contrato` varchar(100) DEFAULT NULL,
  ADD COLUMN `fecha_ingreso` date DEFAULT NULL,
  ADD COLUMN `id_departamento` int(11) DEFAULT NULL,
  ADD COLUMN `id_cargo` int(11) DEFAULT NULL,
  ADD COLUMN `id_horario` int(11) DEFAULT NULL,
  ADD COLUMN `id_salary_level` int(11) DEFAULT NULL,
  ADD COLUMN `salario` decimal(10,2) DEFAULT NULL,
  ADD COLUMN `cuenta_bac` varchar(50) DEFAULT NULL,
  ADD COLUMN `telefono` varchar(20) DEFAULT NULL,
  ADD COLUMN `correo_personal` varchar(100) DEFAULT NULL,
  ADD COLUMN `correo_institucional` varchar(100) DEFAULT NULL,
  ADD COLUMN `num_locker` varchar(20) DEFAULT NULL,
  ADD COLUMN `id_biometrico` int(11) DEFAULT NULL,
  ADD COLUMN `url_contrato` longblob DEFAULT NULL,
  ADD COLUMN `url_solicitud` longblob DEFAULT NULL,
  ADD COLUMN `url_psicometricas` longblob DEFAULT NULL,
  ADD COLUMN `id_candidate_rrhh` int(11) DEFAULT NULL;

ALTER TABLE `doctor`
  ADD COLUMN `id_user` int(11) DEFAULT NULL,
  ADD COLUMN `num_empleado` varchar(50) DEFAULT NULL,
  ADD COLUMN `tipo_empleado` varchar(50) DEFAULT 'Permanente',
  ADD COLUMN `duracion_contrato` varchar(100) DEFAULT NULL,
  ADD COLUMN `fecha_ingreso` date DEFAULT NULL,
  ADD COLUMN `id_departamento` int(11) DEFAULT NULL,
  ADD COLUMN `id_cargo` int(11) DEFAULT NULL,
  ADD COLUMN `id_horario` int(11) DEFAULT NULL,
  ADD COLUMN `id_salary_level` int(11) DEFAULT NULL,
  ADD COLUMN `salario` decimal(10,2) DEFAULT NULL,
  ADD COLUMN `cuenta_bac` varchar(50) DEFAULT NULL,
  ADD COLUMN `telefono` varchar(20) DEFAULT NULL,
  ADD COLUMN `correo_personal` varchar(100) DEFAULT NULL,
  ADD COLUMN `correo_institucional` varchar(100) DEFAULT NULL,
  ADD COLUMN `num_locker` varchar(20) DEFAULT NULL,
  ADD COLUMN `id_biometrico` int(11) DEFAULT NULL,
  ADD COLUMN `url_contrato` longblob DEFAULT NULL,
  ADD COLUMN `url_solicitud` longblob DEFAULT NULL,
  ADD COLUMN `url_psicometricas` longblob DEFAULT NULL,
  ADD COLUMN `id_candidate_rrhh` int(11) DEFAULT NULL;
